name: 'Build Conda'
description: 'Builds a Conda package'
inputs:
  recipe_path: # id of input
    description: 'The path to the recipe from the repo root'
    required: false
    default: 'conda-recipe'
  conda_build_env_filepath:
    description: 'Yaml Conda build environment definition file'
    required: false
    default: 'action_default'
  conda_build_env_name:
    description: 'Conda build environment name'
    required: false
    default: 'action_default'
  base_env_prefix:  # id of input
    description: 'The prefix of the base Conda environment'
    required: false
    default: '/usr/share/miniconda'
  package_artifact_name:
    description: 'Name of the package artifact'
    required: false
    default: 'conda_package'
  test_results_artifact_name:
    description: 'Name of the test results artifact'
    required: false
    default: 'test_results'
  build_options:
    description: 'Options to be passed to conda-build'
    required: false
    default: '-c defaults -c conda-forge'
outputs:
  package-filepath:
    description: "The file path of the generated package"
    value: ${{ steps.build-package.outputs.PACKAGE_PATH }}
runs:
  using: "composite"
  steps:
    - id: build-package
      run: |
        ${{ github.action_path }}/build.sh \
        ${{ inputs.recipe_path }} \
        ${{ inputs.conda_build_env_filepath }} \
        ${{ inputs.conda_build_env_name }} \
        ${{ inputs.base_env_prefix }} \
        '${{ inputs.build_options }}' \
        ${{ github.action_path }} \
        ${{ github.event.repository.name }} \
        ${{ runner.temp }}
      shell: bash -l {0}
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.package_artifact_name }}
        path: ${{runner.temp}}/package_outputs
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.test_results_artifact_name }}
        path: ${{ github.workspace }}/test_results
branding:
  icon: 'package'
  color: 'green'
